.PHONY: rebuild

rebuild: 
	@ls
	# python generate_integer.py &&
	# python generate_fixed_point.py &&
	# python generate_floating_point.py &&
	# python generate_reduction.py &&
	# python generate_mask.py &&
	# python generate_permutation.py